name: Power Platform School Library

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Pozwala na ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Create output directory
        run: |
          mkdir -p out
          echo "✅ Created out/ directory"
          ls -la

      - name: Test Authentication First
        run: |
          echo "Testing authentication..."
          echo "Environment: https://orgbefa339d.crm.dynamics.com"
          echo "User: damjoz1990@learnwithpowerup.onmicrosoft.com"
          echo "Password secret exists: ${{ secrets.PASSWORD != '' }}"

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://orgbefa339d.crm.dynamics.com'
          user-name: 'damjoz1990@learnwithpowerup.onmicrosoft.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'School Library'
          solution-output-file: 'SchoolLibrary.zip'
          working-directory: 'out'
        continue-on-error: true

      - name: Debug - Check export results
        run: |
          echo "=== DEBUGGING EXPORT RESULTS ==="
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of out/ directory:"
          ls -la out/ || echo "❌ out/ directory does not exist"
          echo "Looking for SchoolLibrary.zip:"
          find . -name "SchoolLibrary.zip" -type f 2>/dev/null || echo "❌ SchoolLibrary.zip not found anywhere"
          echo "Looking for any .zip files:"
          find . -name "*.zip" -type f 2>/dev/null || echo "❌ No .zip files found"
          echo "Checking for any error files:"
          find . -name "*.log" -type f 2>/dev/null || echo "No log files found"
          echo "=== END DEBUG ==="

      - name: Try manual pac command
        run: |
          echo "Trying manual pac command for debugging..."
          export PATH="/tmp/powerplatform-actions-*/pac:$PATH"
          pac --version
          echo "Attempting to authenticate..."
          pac auth create --url https://orgbefa339d.crm.dynamics.com --username damjoz1990@learnwithpowerup.onmicrosoft.com --password "${{ secrets.PASSWORD }}" --name debug-profile
          echo "Listing solutions..."
          pac solution list --profile debug-profile || echo "Failed to list solutions"
        continue-on-error: true

      - name: Check if solution file exists
        run: |
          if [ -f "out/SchoolLibrary.zip" ]; then
            echo "✅ SchoolLibrary.zip found - $(ls -lh out/SchoolLibrary.zip)"
          else
            echo "❌ SchoolLibrary.zip NOT found"
            echo "This indicates the export failed silently"
            exit 1
          fi

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/SchoolLibrary.zip'
          solution-folder: 'out/solutions/SchoolLibrary'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://orgbefa339d.crm.dynamics.com'
          user-name: 'damjoz1990@learnwithpowerup.onmicrosoft.com'
          password-secret: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/SchoolLibrary'
          solution-target-folder: 'src/solutions/SchoolLibrary'
          token: ${{ secrets.GIT_SL_TOKEN }}
